### ISSUE TITLE
Week 2 Scrum Update

### ISSUE THREAD

**Issue by MayKikuchi** [mxg895/next-story#16]
csid:
What did you work on this past iteration (2 weeks)?
What were any major issues/challenges you ran into?
What do you plan to work on for this coming iteration (2 weeks)?

**Comment by MayKikuchi** [comment]
csid: i9y9a

What did you work on this past iteration (2 weeks)?
Got the multi card carousel working, styled the media cards, styled and got the media modal up.

What were any major issues/challenges you ran into?
The media modal was a bit tricky in terms of where to put it in the app. I ended up putting it top-level and using redux to open it, but that re-renders the app, so I'm planning to refactor it.

What do you plan to work on for this coming iteration (2 weeks)?
(TBD with team) Api stuff, connecting the media modal to the media page, start connect the reviews to redux.

**Comment by mxg895** [comment]
csid: s5n0b

What did you work on this past iteration (2 weeks)?
- Completed: create-react-app with TS template, installed & set up `eslint`, `react-redux`, `Material-UI`, and `react-router-dom`. Created routes for home, profile, and not found pages using react-router-dom with code-splitting/lazy loading provided by React. Added a lint script to `package.json`, so that we can automatically fix auto-fixable lint errors & show other non-fixable ones with lint errors & warnings when the command `yarn lint` or `npm lint` is called. Regular code reviews on pull requests.
- In progress (on a separate branch not included in the demo): creating the UI for the profile page.

What were any major issues/challenges you ran into?
- Since I was focusing on setting up the basics of our project, most of the challenges were related to picking up the configuration process. Learning about the configurations for eslint and learning about code-splitting for loading different routes and resolving app crashes along the way of the set up process were the most time-consuming parts of the work.

What do you plan to work on for this coming iteration (2 weeks)?
- Finish the UI for the profile page and look into the problem where api(s) is/are working with .js/.jsx but not .ts/.tsx.

**Comment by warrenkwchan** [comment]
csid: q6p0b
What did you work on this past iteration (2 weeks)?
I have created the Login and Sign Up Components, added extra packages like "Material-UI-icon" and "redux-thunk" to facilitate certain works, and set up Movie API ready to be used.

What were any major issues/challenges you ran into?
Most online resources for third party Api  used in React are written in JavaScript so I need to figure out the typescript syntax for the correct conversion. Some errors just don't tell me anything so lots of trials to fix issues.

What do you plan to work on for this coming iteration (2 weeks)?
Integrate my components with main page, start writing services to satisfy our user stories, and decide how we want to structure and store our data in Mongo
